- name: create ec2 & r53 records
  hosts: local
  connection: local
  vars:
    subnet_id: "subnet-0c8dd2998bcbb37fb"
    sg_id: "sg-0bccc85d720ad366e"
    ami_id: "ami-09c813fb71547fc4f"
    instances:
    - mysql
    - backend
    - frontend
    zone: awspractice.shop
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: "t3.micro"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
    loop: "{{ instances }}"
    register: ec2_instances
  